name: Static Analysis

on: [push, pull_request]

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pvs tools
        run: |
          wget -q -O - https://files.pvs-studio.com/etc/pubkey.txt \
            | sudo apt-key add -
          sudo wget -O /etc/apt/sources.list.d/viva64.list \
            https://files.pvs-studio.com/etc/viva64.list
          sudo apt-get update && sudo apt-get upgrade
          sudo apt-get install -y libglu1-mesa-dev mesa-common-dev
          sudo apt-get install -y pvs-studio
          pvs-studio-analyzer credentials ${{secrets.PVS_STUDIO_CREDENTIALS}}

      - name: Build debug config
        run: |
          cmake -B ${{github.workspace}}/Debug_Build_PVS -D CMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_FLAGS="-g" -D CMAKE_EXPORT_COMPILE_COMMANDS=On
          cmake --build ${{github.workspace}}/Debug_Build_PVS -j

      - name: Analyze debug config
        run: |
          pvs-studio-analyzer analyze -f ${{github.workspace}}/Debug_Build_PVS/compile_commands.json -j -e Vendor/

      - name: Convert report
        run: plog-converter -t sarif -o pvs-report.sarif PVS-Studio.log

      - name: Publish report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pvs-report.sarif
          category: PVS-Studio
